import type { ImageMetadata } from 'astro';
import product01 from '@/assets/product/product-01.webp';
import product02 from '@/assets/product/product-02.webp';
import product03 from '@/assets/product/product-03.webp';
import product04 from '@/assets/product/product-04.webp';
import product05 from '@/assets/product/product-05.webp';
import product06 from '@/assets/product/product-06.webp';
import product07 from '@/assets/product/product-07.webp';

/**
 * GENERATED by scripts/lib/asset-pipeline.mjs — do not edit by hand.
 *
 * 7 real product image(s). Three key families resolve here:
 *   - `product-NN`  canonical, derived from position, never from the source filename
 *   - the original scraped filenames, because the Content Agent emits them as `asset` refs
 *   - the template slot keys, re-pointed so no template stock image survives
 */
export const images: Record<string, ImageMetadata> = {
  'product-01': product01,
  'product-02': product02,
  'product-03': product03,
  'product-04': product04,
  'product-05': product05,
  'product-06': product06,
  'product-07': product07,
  'img_0.webp': product01,
  'img_1.webp': product02,
  'img_2.webp': product03,
  'img_3.webp': product04,
  'img_4.webp': product05,
  'img_5.webp': product06,
  'img_6.webp': product07,
  'output/images/img_0.webp': product01,
  'output/images/img_1.webp': product02,
  'output/images/img_2.webp': product03,
  'output/images/img_3.webp': product04,
  'output/images/img_4.webp': product05,
  'output/images/img_5.webp': product06,
  'output/images/img_6.webp': product07,
  'gallery-01': product01,
  'gallery-02': product02,
  'gallery-03': product03,
  'gallery-04': product04,
  'gallery-05': product05,
  'ugc-01': product06,
  'ugc-02': product07,
};
